default: &default
  working_directory: ~/abeja-platform-cli
  docker:
    - image: circleci/python:3.6

test_step: &test_step
  - checkout
  - run:
      name: Install Dependencies
      command: |
        pip install --user poetry
        poetry env use ${ABEJA_CLI_PYTHON_VERSION}
        poetry install
  - run:
      name: Test
      command: |
        case "${CIRCLE_BRANCH}" in
        "master")
          export PLATFORM_ORG="$ORGANIZATION_NAME_PROD"
          export ORGANIZATION_NAME="$ORGANIZATION_NAME_PROD"
          export PLATFORM_USER_ID="$PLATFORM_USER_ID_PROD"
          export PLATFORM_USER_TOKEN="$PLATFORM_USER_TOKEN_PROD"
          export DATALAKE_CHANNEL_ID="$DATALAKE_CHANNEL_ID_PROD"
          export DATALAKE_BUCKET_ID="$DATALAKE_BUCKET_ID_PROD"
          export TRIGGER_INPUT_DATALAKE_ID="$TRIGGER_INPUT_DATALAKE_ID_PROD"
          export TRIGGER_OUTPUT_DATALAKE_ID="$TRIGGER_OUTPUT_DATALAKE_ID_PROD"
          export ABEJA_API_URL='https://api.abeja.io'
          ;;
        *)
          export PLATFORM_ORG="$ORGANIZATION_NAME_DEV"
          export ORGANIZATION_NAME="$ORGANIZATION_NAME_DEV"
          export PLATFORM_USER_ID="$PLATFORM_USER_ID_DEV"
          export PLATFORM_USER_TOKEN="$PLATFORM_USER_TOKEN_DEV"
          export DATALAKE_CHANNEL_ID="$DATALAKE_CHANNEL_ID_DEV"
          export DATALAKE_BUCKET_ID="$DATALAKE_BUCKET_ID_DEV"
          export TRIGGER_INPUT_DATALAKE_ID="$TRIGGER_INPUT_DATALAKE_ID_DEV"
          export TRIGGER_OUTPUT_DATALAKE_ID="$TRIGGER_OUTPUT_DATALAKE_ID_DEV"
          export ABEJA_API_URL='https://api.dev.abeja.io'
          ;;
        esac
        export SAMPLE_MODEL_PATH='https://s3-us-west-2.amazonaws.com/abeja-platform-config-dev'
        make prepare_ci
        make test
        make integration_test

trigger-system-test: &trigger-system-test
  run:
    name: TriggerSystemTest
    command: |
      poetry run python tools/trigger_build_system_test.py

version: 2
jobs:
  codetest35:
    <<: *default
    docker:
      - image: circleci/python:3.5
    environment:
      - ABEJA_CLI_PYTHON_VERSION: "3.5"
    steps: *test_step
  codetest36:
    <<: *default
    environment:
      - ABEJA_CLI_PYTHON_VERSION: "3.6"
    steps: *test_step
  release_package:
    <<: *default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user poetry
            poetry install
      - run:
          name: Deploy
          command: |
            make release
      - *trigger-system-test

  release_rc_package:
    <<: *default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user poetry
            poetry install
      - run:
          name: Deploy_RC
          command: |
            poetry version $(PYTHONPATH=./ poetry run python tools/add_rc_version.py)
            make release
      - *trigger-system-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - codetest35
      - codetest36
      - release_package:
          filters:
            branches:
              only:
                - master
          requires:
            - codetest35
            - codetest36
      - release_rc_package:
          filters:
            branches:
              only:
                - trigger-system-test
                - /^release\/.*/
          requires:
            - codetest35
            - codetest36
