name: Continuous Integration / Delivery for application

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, closed]
  push:
    branches:
      - master
      - release/*
      - master-test

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install --user poetry==1.0.9
          poetry env use 3.8
          poetry install

      - name: Setup variables for Dev environment
        if: ${{ github.ref_name != 'master' }}
        run: |
          echo "PLATFORM_ORG=1113407535106" >> $GITHUB_ENV
          echo "ORGANIZATION_NAME=1113407535106" >> $GITHUB_ENV
          echo "PLATFORM_USER_ID=$PLATFORM_USER_ID_DEV" >> $GITHUB_ENV
          echo "PLATFORM_USER_TOKEN=$PLATFORM_USER_TOKEN_DEV" >> $GITHUB_ENV
          echo "DATALAKE_CHANNEL_ID=1292391500090" >> $GITHUB_ENV
          echo "DATALAKE_BUCKET_ID=1995370125318" >> $GITHUB_ENV
          echo "TRIGGER_INPUT_DATALAKE_ID=2054933523197" >> $GITHUB_ENV
          echo "TRIGGER_OUTPUT_DATALAKE_ID=2054933618430" >> $GITHUB_ENV
          echo "ABEJA_API_URL=https://api.dev.abeja.io" >> $GITHUB_ENV
        env:
          PLATFORM_USER_ID_DEV: ${{ secrets.PLATFORM_USER_ID_DEV }}
          PLATFORM_USER_TOKEN_DEV: ${{ secrets.PLATFORM_USER_TOKEN_DEV }}

      - name: Setup variables for Prod environment
        if: ${{ github.ref_name == 'master' }}
        run: |
          echo "PLATFORM_ORG=1285934979127" >> $GITHUB_ENV
          echo "ORGANIZATION_NAME=1285934979127" >> $GITHUB_ENV
          echo "PLATFORM_USER_ID=$PLATFORM_USER_ID_PROD" >> $GITHUB_ENV
          echo "PLATFORM_USER_TOKEN=$PLATFORM_USER_TOKEN_PROD" >> $GITHUB_ENV
          echo "DATALAKE_CHANNEL_ID=1293163161758" >> $GITHUB_ENV
          echo "DATALAKE_BUCKET_ID=1995371681794" >> $GITHUB_ENV
          echo "TRIGGER_INPUT_DATALAKE_ID=2054929723742" >> $GITHUB_ENV
          echo "TRIGGER_OUTPUT_DATALAKE_ID=2054929811807" >> $GITHUB_ENV
          echo "ABEJA_API_URL=https://api.dev.abeja.io" >> $GITHUB_ENV
        env:
          PLATFORM_USER_ID_PROD: ${{ secrets.PLATFORM_USER_ID_PROD }}
          PLATFORM_USER_TOKEN_PROD: ${{ secrets.PLATFORM_USER_TOKEN_PROD }}

      - name: Unit test
        run: | 
          make prepare_ci
          make test
#          make integration_test
        env:
          NUM_TEST_PROCESS: 1

  cd:
    runs-on: ubuntu-latest
    # if: ${{ startsWith(github.ref_name, 'release/') || github.ref_name == 'master' }}
    if: ${{ startsWith(github.ref_name, 'release/') || github.ref_name == 'master-test' }}
    needs:
      - ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install --user poetry
          poetry install

      - name: Deploy_RC
        if: ${{ startsWith(github.ref_name, 'release/') }}
        run: |
          poetry version $(PYTHONPATH=./ poetry run python tools/add_rc_version.py)
          # make release
          make release-test
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

      - name: Deploy
        # if: ${{ github.ref_name== 'master' }}
        if: ${{ github.ref_name == 'master-test' }}
        run: |
          # make release
          make release-test
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
